/*
Problem 2
19 October 2001

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

def cache = [1: 1, 2: 2]
def fb = 0, i = 1, sum = 0
def fib
fib = { cache[it] = cache[it] ?: fib(it - 1) + fib(it - 2) }
while (fb < 4000000) {
  println sum
  fb = fib(i++)
  sum += fb % 2 == 0 ? fb : 0
}
println sum