/*
Triangular, pentagonal, and hexagonal
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

 */

def triangleNum(long n) {
  n * (n + 1) / 2.0
}

def pentagonal = { n ->
  (n * (3 * n - 1)) / 2
}
def invP = { p ->
  def index = (Math.sqrt(24 * p + 1) + 1) / 6
  index - index.trunc() == 0 ? index : 0
}

def hexagonal = { n ->
  n * (2 * n - 1)
}
def invH = { p ->
  def index = (Math.sqrt(8 * p + 1) + 1) / 4
  index - index.trunc() == 0 ? index : 0
}

def n = 285
def t = triangleNum(++n)
while (!(invP(t) != 0 && invH(t) != 0)) {
  t = triangleNum(++n)
}
println "T$n is the next triangle number($t) that is also a pentagonal and hexagonal."